import 'dotenv/config';
import { db, schema } from './index.js';

const now = Date.now();
const hoursAgo = (h) => new Date(now - h * 60 * 60 * 1000);

const orders = [
  {
    id: 'ORD-1001',
    title: 'Pallet of office supplies',
    pickupAddress: '90 Rivonia Rd, Sandton, Johannesburg',
    deliveryAddress: '15 Tyrwhitt Ave, Rosebank, Johannesburg',
    pickupLat: -26.1076,
    pickupLng: 28.0567,
    deliveryLat: -26.1467,
    deliveryLng: 28.0436,
    distanceKm: 6.4,
    status: 'pending',
    priority: 'medium',
    estimatedMinutes: 18,
    itemCount: 4,
    createdAt: hoursAgo(1),
  },
  {
    id: 'ORD-1002',
    title: 'Refrigerated medical samples',
    pickupAddress: 'Lone Creek Cres, Waterfall City, Midrand',
    deliveryAddress: '298 Helen Joseph St, Pretoria',
    pickupLat: -25.9968,
    pickupLng: 28.1123,
    deliveryLat: -25.7479,
    deliveryLng: 28.1879,
    distanceKm: 32.1,
    status: 'assigned',
    priority: 'high',
    estimatedMinutes: 45,
    itemCount: 2,
    createdAt: hoursAgo(3),
    assignedAt: hoursAgo(2),
  },
  {
    id: 'ORD-1003',
    title: 'Furniture delivery - 3 seater couch',
    pickupAddress: 'Cnr Witkoppen & Main Rd, Fourways, Johannesburg',
    deliveryAddress: '1 Maude St, Sandton, Johannesburg',
    pickupLat: -26.0125,
    pickupLng: 28.0079,
    deliveryLat: -26.1070,
    deliveryLng: 28.0567,
    distanceKm: 14.8,
    status: 'in_progress',
    priority: 'high',
    estimatedMinutes: 35,
    itemCount: 1,
    createdAt: hoursAgo(4),
    assignedAt: hoursAgo(3),
    navigationStartedAt: hoursAgo(1),
    routePolyline: '_p~iF~ps|U_ulLnnqC_mqNvxq`@',
  },
  {
    id: 'ORD-1004',
    title: 'Grocery restock - dry goods',
    pickupAddress: 'Cnr Carl Cronje Dr & Bill Bezuidenhout Ave, Bellville, Cape Town',
    deliveryAddress: '81 Main Rd, Sea Point, Cape Town',
    pickupLat: -33.8869,
    pickupLng: 18.6296,
    deliveryLat: -33.9167,
    deliveryLng: 18.3833,
    distanceKm: 24.6,
    status: 'completed',
    priority: 'medium',
    estimatedMinutes: 40,
    itemCount: 12,
    createdAt: hoursAgo(26),
    assignedAt: hoursAgo(25),
    navigationStartedAt: hoursAgo(24),
    navigationEndedAt: hoursAgo(23.3),
    completedAt: hoursAgo(23),
    actualDistanceMeters: 25430,
    actualDurationSeconds: 2580,
    safetyScore: 92.5,
    safetyEvents: 1,
    averageAttention: 0.88,
    eventBreakdown: { harshBraking: 1, speeding: 0, phoneUsage: 0 },
  },
  {
    id: 'ORD-1005',
    title: 'Document courier - signed contracts',
    pickupAddress: '1 Bridge Cl, Century City, Cape Town',
    deliveryAddress: 'Foreshore, Cape Town City Centre',
    pickupLat: -33.8903,
    pickupLng: 18.5125,
    deliveryLat: -33.9180,
    deliveryLng: 18.4233,
    distanceKm: 9.7,
    status: 'cancelled',
    priority: 'low',
    estimatedMinutes: 22,
    itemCount: 1,
    createdAt: hoursAgo(8),
  },
  {
    id: 'ORD-1006',
    title: 'Hardware store bulk order',
    pickupAddress: '5 Le Roux Rd, Halfway House, Midrand',
    deliveryAddress: 'Cnr Voortrekker Rd & Kelvin Dr, Edenvale',
    pickupLat: -25.9894,
    pickupLng: 28.1287,
    deliveryLat: -26.1378,
    deliveryLng: 28.1494,
    distanceKm: 21.3,
    status: 'pending',
    priority: 'low',
    estimatedMinutes: 38,
    itemCount: 7,
    createdAt: hoursAgo(0.5),
  },
];

await db.insert(schema.orders).values(orders).onConflictDoNothing();

console.log(`Seeded ${orders.length} orders (existing IDs left untouched).`);
process.exit(0);
